### ISSUE TITLE
[Discussion] Publishing the new version to npm

### ISSUE THREAD

**Issue by Ilshidur** [lapwinglabs/x-ray-crawler#11]
Currently, the latest version on npm is `2.0.2` and got released 2 years ago.
I think it would be good to publish the changes we made few weeks ago.

I can release the `2.0.3` version, as I have the rights to publish the package on npm.
Just wanted to know your opinion on this (@matthewmueller @jhwohlgemuth).

**Comment by jhwohlgemuth** [comment]
@Ilshidur 
Totally agree. Especially since the security fixes will not appear “fixed” until a new version is published...

**Comment by Ilshidur** [comment]
Published the `2.0.3` version 👍
