### ISSUE TITLE
Remediate vulnerabilities introduced by out-dated versions of superagent and ms 

### ISSUE THREAD

**Issue by jhwohlgemuth** [lapwinglabs/x-ray-crawler#6]
Certain versions of [qs](https://github.com/ljharb/qs) have a [vulnerability](https://snyk.io/vuln/npm:qs:20170213) that has been patched in recent versions (and back-ported to certain older versions).

In any case, `x-ray-crawler` is affected by the vulnerability through an old version of [`superagent`](https://github.com/visionmedia/superagent) (`superagent` has since updated it's `qs` dependency and is no longer affected by the vulnerability)

Upgrading to the current version of `superagent` would clear the vulnerability for this project (and `x-ray` which depends on it).

[ms](https://github.com/zeit/ms) also has a [vulnerability](https://snyk.io/vuln/npm:ms:20170412) which can be fixed by upgrading to [version ^2.0.0](https://github.com/zeit/ms/releases/tag/2.0.0)

I am a big fan of the `x-ray` project and want it to look and perform as good as it can 🎩 ❇️ .

If you like, I could make a PR for this upgrade.

**Comment by Ilshidur** [comment]
[Opened a pull request](https://github.com/lapwinglabs/x-ray-crawler/pull/7). It would be nice if someone could check this out :-)

**Comment by Ilshidur** [comment]
Fix : https://github.com/lapwinglabs/x-ray-crawler/commit/50f171c116e97d204b0aa7c416561d29f87e820c.
